version: '2'
services:
 da1:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
  networks:
    default:
      ipv4_address: 172.18.0.2
 da2:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
  networks:
    default:
      ipv4_address: 172.18.0.3
 da3:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
    networks:
      default:
        ipv4_address: 172.18.0.4
 relay01:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.11
 relay02:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.12
 relay03:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.13
 relay04:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.14
 relay05:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.15
 relay06:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.16
 relay07:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.17
 relay08:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.18
 relay09:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.19
 relay10:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.20
 relay11:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.21
 relay12:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.22
 relay13:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.23
 relay14:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.24
 relay15:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.25
 exit01:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.31
 exit02:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.32
 exit03:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.33
 exit04:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.34
 exit05:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.35
 exit06:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.36
 exit07:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.37
 exit08:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.38
 exit09:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.39
 exit10:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.40
 client:
  image: lunaken/narutor:0.4.4
  ports:
    # Setups a listener on host machine
    - "9050:9050"
    - "9051:9051"
  volumes:
    - ./tor:/tor
  environment:
    ROLE: CLIENT
  depends_on: 
    - da1
    - da2
    - da3
  networks:
    default:
      ipv4_address: 172.18.0.100
 hs:
  image: lunaken/narutor:0.4.4
  #expose:
  #  - "80"
  environment:
    ROLE: HS
    # This will create a hidden service that points to
    # the service "web" which is runing nginx. You can 
    # change this to whatever ip or hostname you want
    TOR_HS_PORT: "80"
    TOR_HS_ADDR: "web"
  volumes:
    - ./tor:/tor
  depends_on:
    - da1
    - da2
    - da3
  links:
    - web
  networks:
    default:
      ipv4_address: 172.18.0.5
 web:
  image: nginx
  #expose:
  #  - "80"
  networks:
    default:
      ipv4_address: 172.18.0.5
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

